=== KIZI/IRAPI/focusedcrawler/src/main/resources/ex/data/eol.dtd
<!-- 
     $Id: eol.dtd 1877 2009-03-28 13:19:38Z labsky $
     A DTD for extraction ontology language 
-->

<!ELEMENT model (class|units|datatypes|import|base|script|finally|classifier)* >
<!ATTLIST model
  name         CDATA    #IMPLIED
  version      CDATA    #FIXED  '0.2' >

<!ELEMENT class (attribute|axiom|pattern|script|classifier)* >
<!ATTLIST class
  id           CDATA    #REQUIRED 
  prune        CDATA    #IMPLIED
  counts       CDATA    #IMPLIED
  enabled      (yes|no|true|false|1|0) "1"
  log          (yes|no|true|false|1|0) "0" 
  learnFormatting  (yes|no|true|false|1|0) "0"
  fmtPrecFactor    CDATA   #IMPLIED
  fmtRecallFactor  CDATA   #IMPLIED
  >

<!-- name may be ommited if the attribute extends some base atribute and the names remain identical -->
<!ELEMENT attribute (pattern|value|context|axiom|classifier)* >
<!ATTLIST attribute
  id           CDATA    #REQUIRED
  type         CDATA    #IMPLIED
  dbname       CDATA    #IMPLIED
  dim          CDATA    "1"
  card         CDATA    #IMPLIED
  units        CDATA    #IMPLIED
  abstract     CDATA    #IMPLIED
  extends      CDATA    #IMPLIED
  prior        CDATA    "-1"
  mutable      CDATA    "0"
  eng          CDATA    "0.75"
  prune        CDATA    #IMPLIED 
  enabled      (yes|no|true|false|1|0) "1"
  log          (yes|no|true|false|1|0) "0" 
  learnFormatting  (yes|no|true|false|1|0) "0"
  fmtPrecFactor    CDATA   #IMPLIED
  fmtRecallFactor  CDATA   #IMPLIED
  >

<!-- names often used in text to refer to this attribute -->
<!-- now ignored, in future may be used to automatically generate context patterns -->
<!ELEMENT name (#PCDATA) >
<!ATTLIST name >

<!-- attributes and children of this attribute constrain values of this attribute -->
<!ELEMENT value (pattern|distribution|length|card|contains|axiom|transform|refers|and|or)* >
<!ATTLIST value >

<!ELEMENT context (pattern|and|or)* >
<!ATTLIST context >

<!-- specifies distribution of (1) numeric attribute's value, (2) textual attribute's length -->
<!ELEMENT distribution (#PCDATA|enum)* >
<!ATTLIST distribution
  min          CDATA    #IMPLIED
  max          CDATA    #IMPLIED
  unit         CDATA    #IMPLIED 
  type         (minmax|table|normal|mixture)   "minmax" >

<!ELEMENT enum (#PCDATA) >
<!ATTLIST enum
  p            CDATA    #IMPLIED
  cover        CDATA    #IMPLIED >

<!ELEMENT or (pattern)* >
<!ATTLIST or >

<!ELEMENT and (pattern)* >
<!ATTLIST and 
  cover        CDATA    "-1"
  p            CDATA    "-1" >

<!ELEMENT pattern (#PCDATA|att|tok|pattern|unit|tag|lab|cond)* >
<!-- ignore: e.g. 'case' or 'lemma': by default ignore case or different forms of single lemma
cover: percentage of attribute values covered by the contained patterns
p: P(attribute | some_pattern_matches)
src: text file containing per-line phrases (alternatively, content may be in PCDATA)
type: reserved for future alternative list formats
encoding: src file's encoding 
ignore: list of ignorable properties; e.g. "case, lemma"
case: force all tokens in pattern to be of particular case; e.g. "CA | UC"
The following is only supported for class-level axioms and class-level patterns of type=script|pattern:
cond attribute: any | all | n/a (whether the attributes referenced from the pattern must be defined for the instance)
cond child (overrides cond attribute): script expression which must evaluate to true in order for the pattern to apply
-->
<!ATTLIST pattern
  id           CDATA    #IMPLIED
  ref          CDATA    #IMPLIED
  src          CDATA    #IMPLIED
  type         (pattern|list|script|format|instance|xpath)    "pattern"
  encoding     CDATA    "utf-8"
  ignore       CDATA    #IMPLIED
  case         CDATA    #IMPLIED
  cover        CDATA    "-1"
  p            CDATA    "-1"
  length       CDATA    #IMPLIED
  cond         CDATA    #IMPLIED
  within       CDATA    #IMPLIED
  greedy       (no|yes|true|false|1|0) "0"
  feature      (no|yes|true|false|1|0) "1" 
  enabled      (yes|no|true|false|1|0) "1"
  linear       (yes|no|true|false|1|0) "0"
  neg          (yes|no|true|false|1|0) "0"
  log          (yes|no|true|false|1|0) "0">

<!ELEMENT length (distribution) >
<!-- length in child components: either tokens or contained attributes -->
<!ATTLIST length >

<!ELEMENT card (distribution) >
<!-- attribute cardinality distribution; specify this if the dist is known; use the card attribute otherwise to just specify min and max -->
<!ATTLIST card >

<!-- specifies attributes which MAY be contained in the parent aggregate attribute -->
<!ELEMENT contains (att*) >
<!ATTLIST contains >

<!-- ref: id of the referenced attribute; following attributes only used within 'contains':
card: how many different values the referenced attribute may have in this context
cover: percentage of the aggregate attribute values containing the referenced attribute
p: p(aggregate_attribute_contains_referenced | referenced_attribute) -->
<!ELEMENT att (card?) >
<!ATTLIST att
  ref          CDATA    #REQUIRED
  card         CDATA    "1"
  cover        CDATA    "-1"
  p            CDATA    "-1" >

<!ELEMENT axiom (#PCDATA|cond)* >
<!ATTLIST axiom
  id           CDATA    #IMPLIED
  cond         CDATA    #IMPLIED
>

<!ELEMENT transform (#PCDATA|cond)* >
<!ATTLIST transform
  id           CDATA    #IMPLIED
  cond         CDATA    #IMPLIED
>

<!ELEMENT refers (#PCDATA)* >
<!ATTLIST refers >

<!-- unit definitions -->
<!ELEMENT units (quantity*)>
<!ATTLIST units >

<!ELEMENT quantity (unit*)>
<!ATTLIST quantity
  id           CDATA    #REQUIRED
  baseunit     CDATA    #REQUIRED>

<!ELEMENT unit (#PCDATA)>
<!ATTLIST unit
  id           CDATA    #IMPLIED
  convert      CDATA    #IMPLIED>

<!-- tok: exactly 1 token specified using attributes.
pcdata: token text, if constrained to a specific word (also see ignore)
ignore: if text is specified, set ignore='case' or ignore='lemma' to broaden matches
type: constraint for token type: e.g. ALPHANUM, or combination ALPHANUM|ALPHA|NUM
case: constraint for token case: e.g. LC,UC,CAP
pos: constraint for pos tag: e.g. NP or JJ|CD -->
<!ELEMENT tok (#PCDATA)>
<!ATTLIST tok
  ignore       CDATA    #IMPLIED
  type         CDATA    #IMPLIED
  case         CDATA    #IMPLIED
  pos          CDATA    #IMPLIED >

<!ELEMENT tag EMPTY >
<!ATTLIST tag
  name         CDATA    #IMPLIED
  type         CDATA    #IMPLIED
  form         CDATA    #IMPLIED >

<!ELEMENT lab EMPTY >
<!ATTLIST lab
  name         CDATA    #IMPLIED 
  neg          (yes|no|true|false|1|0) "0" >

<!-- Deprecated: Phrase can be part of a token pattern definition. 
It matches a phrase which: 
a) matches a character-level regexp specified as phrase content (overrides tokenizer),
b) has the requested label set.
-->
<!-- <!ELEMENT phr (#PCDATA)> <!ATTLIST phr  label        CDATA    #IMPLIED > -->

<!-- Instead of <phr>, use e.g. <lab name="^S|div"/> to match label starts, ends or bodies.
     To match phrases spanning multiple tokens, either:
     - use regular token-level token patterns, or
     - TODO: in the <tokenizer> section under <model>, define user-defined token types by 
       assigning a token type to a set of char-level regular expressions that match raw text of document 
       before default tokenization is done by ex. A single token of the defined type is created for 
       anything that matches at least one of the corresponding regexps. It is possible to specify 
       for each user-defined token type whether it is allowed to cross tag boundaries (and for which tags). 
-->

<!ELEMENT datatypes (pattern)* >
<!ATTLIST datatypes >

<!ELEMENT import EMPTY >
<!ATTLIST import
  model        CDATA    #REQUIRED
>

<!ELEMENT base EMPTY >
<!ATTLIST base
  url          CDATA    #REQUIRED
>

<!ELEMENT script (#PCDATA)* >
<!ATTLIST script
  src          CDATA    #IMPLIED
>

<!ELEMENT classifier (feature|param)* >
<!ATTLIST classifier
  id           CDATA    #REQUIRED
  datasource   CDATA    #REQUIRED
  classtype    (attribute|instance)   #REQUIRED
  name         CDATA    #REQUIRED
  model        CDATA    #REQUIRED
  elements     CDATA    #REQUIRED
  confidencethreshold CDATA #IMPLIED
>

<!ELEMENT feature EMPTY >
<!ATTLIST feature
  type         (model|ngram)  #REQUIRED
  ignore       CDATA          #IMPLIED
  length       CDATA          #IMPLIED
  minocc       CDATA          #IMPLIED
  maxcnt       CDATA          #IMPLIED
  mi           CDATA          #IMPLIED
  position     CDATA          #IMPLIED
  source       (document|file)  #IMPLIED
  book         CDATA          #IMPLIED
>

<!ELEMENT param (#PCDATA)* >
<!ATTLIST param
  name         CDATA    #REQUIRED
>

<!ELEMENT finally (script)* >
<!ATTLIST finally >

<!-- 
$Log: eol.dtd,v $
Revision 1.17  2007/02/03 22:15:25  labsky
support for AC IC patterns, length distro evidence, many fixes, new bugs

Revision 1.16  2007/01/16 01:21:24  labsky
type for distr not mandatory

Revision 1.15  2007/01/14 23:22:36  labsky
new pattern types supported: format and script, adding AC prune prob threshold

Revision 1.14  2007/01/07 22:43:14  labsky
adding distributions for length, cardinality, numeric values

Revision 1.13  2007/01/05 22:27:52  labsky
adding eng (engaged prob) as attribute of the <attribute> tag

Revision 1.12  2006/10/12 08:17:43  labsky
large 'list' support for pattern

Revision 1.11  2006/03/11 22:31:45  labsky
adding prior=-1 to attribute, defaulting p,cover=-1

Revision 1.10  2006/02/27 17:56:58  labsky
- merging pattern + list into pattern
- adding datatypes section for dtype patterns
- adding import
- adding enum to distribution

Revision 1.9  2006/02/13 00:04:19  labsky
pattern-related changes

Revision 1.8  2006/02/06 23:28:10  labsky
simplifications and support for expressing token patterns,
name conveted to list, element nesting clarified

Revision 1.7  2005/12/12 22:59:21  labsky
adsing mutable attribute to <attribute> - denotes if attribute
can change from day to day for the very same product (e.g. price)

Revision 1.6  2005/11/23 14:07:29  labsky
adding dbname xml attribute of tag <attribute>,
used to store attribute values in object_table

Revision 1.5  2005/11/16 10:47:06  labsky
minor changes

-->

=== KIZI/IRAPI/focusedcrawler/src/main/resources/ex/data/datatypes.xml
<?xml version="1.0" ?>
<!DOCTYPE model SYSTEM "eol.dtd">
<!--
     $Id: datatypes.xml 1438 2008-04-26 00:04:29Z labsky $
     Definition of generic token patterns used to to extract values having a certain datatype
-->
<model>
<datatypes>

 <!-- textual -->
 <pattern id="name">
   <tok />{1,10}
 </pattern>
 <pattern id="text">
   <tok />{1,200}
 </pattern>
 <pattern id="xml">
   <tok />{1,200}
 </pattern>
  
 <!-- numbers -->
 <pattern id="int">
   <tok type="INT"/>+
 </pattern>
 <pattern id="float">
   <tok type="INT"/>+ (.|,) <tok type="INT"/>+
   <tok type="INT"/>* <tok type="FLOAT"/>
 </pattern>
 
 <!-- boolean -->
 <pattern id="bool" ignore="case">
   yes | y | true | 1 | ano | a
   no | n | n.a. | n/a | none | false | 0 | ne
 </pattern>
 
 <!-- time -->
 <pattern id="minutes">
 00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19
 20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39
 40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59
 </pattern>
 <pattern id="hours">
 01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23
 1|2|3|4|5|6|7|8|9
 </pattern>
 <pattern id="time">
   <pattern ref="hours"/> (:|.|-)? <pattern ref="minutes"/>
 </pattern>
 
 <!-- date -->
 <pattern id="day">
 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31
 1st|2nd|3rd|4th|5th|6th|7th|8th|9th|10th|11th|12th|13th|14th|15th|16th|17th|18th|19th|20th|21st|22nd|23rd|24th|25th|26th|27th|28th|29th|30th|31st
 </pattern>
 <pattern id="day_name" ignore="case">
  monday|tuesday|wednesday|thursday|friday|saturday|sunday
  (mon|tue|wed|thu|fri|sat|sun) .?
 </pattern>
 <pattern id="month" ignore="case">
 1|jan|january
 2|feb|february
 3|mar|march
 4|apr|april
 5|may
 6|jun|june
 7|jul|july
 8|aug|august
 9|sep|september
 10|oct|october
 11|nov|november
 12|dec|december
 </pattern>
 <pattern id="year">
 1950|1951|1952|1953|1954|1955|1956|1957|1958|1959|1960|1961|1962|1963|1964|1965
 1966|1967|1968|1969|1970|1971|1972|1973|1974|1975|1976|1977|1978|1979|1980|1981
 1982|1983|1984|1985|1986|1987|1988|1989|1990|1991|1992|1993|1994|1995|1996|1997
 1998|1999|2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|2010|2011|2012|2013
 2014|2015|2016|2017|2018|2019|2020|2021|2022|2023|2024|2025|2026|2027|2028|2029
 2030|2031|2032|2033|2034|2035|2036|2037|2038|2039|2040|2041|2042|2043|2044|2045
 2046|2047|2048|2049|2050
 80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|00|01|02|03|04|05|06|07|08|09
 </pattern>
 <pattern id="date">
   <pattern ref="day"/> (.|/|-) <pattern ref="month"/> ((.|/|-)? <pattern ref="year"/>)?
   <pattern ref="month"/> (.|/|-)? <pattern ref="year"/>
   (<pattern ref="year"/> (/|-))? <pattern ref="month"/> (/|-) <pattern ref="day"/>
   <pattern ref="year"/> (/|-) <pattern ref="month"/>
 </pattern>

</datatypes>
</model>

=== KIZI/IRAPI/focusedcrawler/src/main/resources/ex/data/media/media.xml
<?xml version="1.0" ?>
<!DOCTYPE model SYSTEM "../eol.dtd">
<!--
     $Id: contact_en6.xml 1880 2009-03-28 13:23:28Z labsky $
     Extraction ontology for initial medieq criteria
-->
<model name="media">

<import model="../datatypes.xml" />

<!-- functions used by some script axioms -->
<!-- <script src="media.js" /> -->

<!-- all references to resources below will be resolved relative to this base url -->
<base url="../../../data"/>

<class id="mrec" prune="0.05">


  <pattern id="media_next_to_title" type="pattern" cover="0.9" log="0" enabled="1">
    ^ ( ($title $media) | ($media $title) ) $
  </pattern>
  
  <!--
  p="0.6" 
  <pattern cover="0.05" p="-1.0" type="format"> has_one_parent </pattern>
  <pattern cover="0.03" p="-1.0" type="format"> fits_in_parent </pattern>
  <pattern cover="1"    p="-1.0" type="format"> no_crossed_inline_tags </pattern>
  <pattern cover="0.03" p="-1.0" type="format"> no_crossed_block_tags </pattern>
  -->
  <pattern cover="0.05" type="format"> no_crossed_block_tags </pattern>
  
  <attribute id="title" type="name" card="1" prior="0.01" eng="1" log="1" prune="0.1">
    <pattern id="words1"> <tok/> </pattern>
    <pattern id="words2"> <tok/>{2,5} </pattern>
    <pattern id="words3"> <tok/>{6,20} </pattern>

    <value>
      <or>
        <pattern p="0.5"> <tag name="caption"/> <pattern ref="words1"/> <tag name="/caption"/> </pattern>
        <pattern p="0.6"> <tag name="caption"/> <pattern ref="words2"/> <tag name="/caption"/> </pattern>
        <pattern p="0.7"> <tag name="caption"/> <pattern ref="words3"/> <tag name="/caption"/> </pattern>
      </or>
      <or>
        <pattern p="0.5"> <tag name="h1"/>      <pattern ref="words1"/> <tag name="/h1"/> </pattern>
        <pattern p="0.6"> <tag name="h1"/>      <pattern ref="words2"/> <tag name="/h1"/> </pattern>
        <pattern p="0.7"> <tag name="h1"/>      <pattern ref="words3"/> <tag name="/h1"/> </pattern>
      </or>
      <or>
        <pattern p="0.5"> <tag name="h2"/>      <pattern ref="words1"/> <tag name="/h2"/> </pattern>
        <pattern p="0.6"> <tag name="h2"/>      <pattern ref="words2"/> <tag name="/h2"/> </pattern>
        <pattern p="0.7"> <tag name="h2"/>      <pattern ref="words3"/> <tag name="/h2"/> </pattern>
      </or>
      <or>
        <pattern p="0.5"> <tag name="h3"/>      <pattern ref="words1"/> <tag name="/h3"/> </pattern>
        <pattern p="0.6"> <tag name="h3"/>      <pattern ref="words2"/> <tag name="/h3"/> </pattern>
        <pattern p="0.7"> <tag name="h3"/>      <pattern ref="words3"/> <tag name="/h3"/> </pattern>
      </or>
      <or>
        <pattern p="0.5"> <tag name="h4"/>      <pattern ref="words1"/> <tag name="/h4"/> </pattern>
        <pattern p="0.6"> <tag name="h4"/>      <pattern ref="words2"/> <tag name="/h4"/> </pattern>
        <pattern p="0.7"> <tag name="h4"/>      <pattern ref="words3"/> <tag name="/h4"/> </pattern>
      </or>
      <or>
        <pattern p="0.5"> <tag name="h5"/>      <pattern ref="words1"/> <tag name="/h5"/> </pattern>
        <pattern p="0.6"> <tag name="h5"/>      <pattern ref="words2"/> <tag name="/h5"/> </pattern>
        <pattern p="0.7"> <tag name="h5"/>      <pattern ref="words3"/> <tag name="/h5"/> </pattern>
      </or>

      <length><distribution min="1" max="30" /></length>

      <pattern cover="1" type="format"> has_one_parent </pattern>
      <pattern cover="1" type="format"> fits_in_parent </pattern>
      <pattern cover="1" type="format"> no_crossed_inline_tags </pattern>
      <pattern cover="1" type="format"> no_crossed_block_tags </pattern>
    </value>
  </attribute>

  <attribute id="media" type="xml" card="1" prior="0.01" eng="1" log="1" enabled="1">
     
    <!-- can't include xpath patterns in regular tokenpatterns yet: 
    <pattern id="xp" type="xpath"> //*[self::img or self::embed or self::video or self::object]/@src </pattern>	
    <value> <pattern cover="0.05"  p="0.5"> <pattern ref="xp"/> </pattern> </value>
	-->
	
	<value>
	  <!-- select all petential images and videos in document -->
      <pattern id="xp1" type="xpath" p="0.5" log="1">
        //*[local-name()='img' or local-name()='embed' or local-name()='video' or local-name()='object']
      </pattern>
      
      <!-- lowercase (or true case) tag names result from XHTML pages, but HTML pages always yield uppercase elements in the Neko implementation -->
      <pattern id="xp1" type="xpath" p="0.5" log="1">
        //*[local-name()='IMG' or local-name()='EMBED' or local-name()='VIDEO' or local-name()='OBJECT']
      </pattern>
	</value>
	
  </attribute>

  <attribute id="email" type="name" card="0-1" eng="0" log="1" prune="0.2">
    <value>
      <pattern cover="0.98" ignore="case" p="0.9" log="0">
        <tok type="EMAIL" />
        <tok type="ALPHA|ALPHANUM"/> ( . <tok type="ALPHA|ALPHANUM"/> )? at ( <tok type="ALPHA|ALPHANUM"/> . ){1,3} (cz|org|com|eu|de|sk|pl|es|gr|ch|fi|gb|uk|hu|au|ru|it|ca)
      </pattern>
      <length><distribution min="1" max="3" /></length>
    </value>
    <context>
      <pattern cover="0.1" ignore="case,lemma" p="0.3"> ( email | e-mail | e .? mail ) :? $ </pattern>
    </context>
  </attribute>

  <attribute id="phone" type="name" card="0-1" eng="0" prune="0.2">
    <pattern id="prefix_bracketed"> \( \+? <tok type="INT">^\d{1,4}$</tok> \) </pattern>
    <pattern id="prefix_unbracketed">  \+? <tok type="INT">^\d{1,4}$</tok> </pattern>
    <pattern id="num_wo_prefix"> 
      (-|/)? <tok type="INT">^\d{5,9}$</tok>
      ((-|/)? <tok type="INT">^\d{3,4}$</tok>){2,3}
      ((-|/)? <tok type="INT">^\d{2,3}$</tok>){2,4}
      (-|/)? <tok type="INT">^\d{1,2}$</tok> -? <tok type="INT">^\d{3,5}$</tok>{2,3}
      <tok type="INT">^\d$</tok> (-? <tok type="INT">^\d{3,4}$</tok>){2,3}
    </pattern>
    <pattern id="cc"> \+? <tok type="INT">^\d{1,3}$</tok> (-|/)? </pattern>
    <value>
      <or>
        <pattern id="v1" cover="0.01" p="0.95" log="0">
          <pattern ref="cc"/>? <pattern ref="prefix_bracketed"/> <pattern ref="num_wo_prefix"/>
        </pattern>
        <pattern id="v2" cover="0.01" p="0.65">
          <pattern ref="prefix_unbracketed"/> <pattern ref="num_wo_prefix"/>
        </pattern>
        <pattern id="v3" cover="0.01" p="0.05"> 
           <pattern ref="cc"/>? <tok type="INT"/> ( -? <tok type="INT"/> ){1,2}
        </pattern>
        <pattern id="v4" cover="0.01" p="0.65">
          <tok type="INT">^\d{3}$</tok> ( - <tok type="INT">^\d{3,8}$</tok> ){1}
          <tok type="INT">^\d{2,3}$</tok> ( - <tok type="INT">^\d{3,4}$</tok> ){2,3} 
        </pattern>
        <pattern id="v5" cover="-1" p="0.05"> <tok type="INT"/>{2,4} </pattern>
      </or>
 
      <length><distribution min="1" max="10" /></length>
      <pattern cover="1.0" p="-1" type="format"> has_one_parent </pattern>
      <pattern cover="0.02" p="-1" type="format"> fits_in_parent </pattern>
      <pattern cover="1.0" p="-1" type="format"> no_crossed_inline_tags </pattern>
      <pattern cover="1.0" p="-1" type="format"> no_crossed_block_tags </pattern>
            
      <!-- restrictions -->
      <pattern cover="0.01" p="0.001"> <pattern ref="_datatypes.year"/> - <pattern ref="_datatypes.year"/> </pattern>
           
      <pattern cover="1.0" p="-1.0" type="pattern"> 
        <pattern ref="v1"/> | <pattern ref="v2"/> | <pattern ref="v3"/> | <pattern ref="v4"/> | <pattern ref="v5"/>
      </pattern>
    </value>
    <context>
      <pattern cover="0.03" ignore="case" p="0.4"> 
         ( tel .? | phone | telephone | cell | cellphone | cellular | line | ext .? | fax 
           tollfree | toll -? free | number is | numbers are ) :? $
      </pattern>
      <pattern cover="0.03" ignore="case" p="0.4">
        $ \(? (fax | cell | cellphone | tollfree | toll -? free) \)?
      </pattern>
      <pattern cover="-1" p="0.001"> <tok type="INT"/> <lab name="INLINE|BLOCK|BR$" neg="1"/> $ </pattern>
      <pattern cover="-1" p="0.001"> $ <lab name="INLINE|BLOCK|BR$" neg="1"/> <tok type="INT"/> </pattern>
    </context>
  </attribute>
  
</class>

<!-- 
<finally>
  <script> transformContacts(); </script>
</finally>
 -->
 
</model>

=== KIZI/IRAPI/focusedcrawler/src/main/resources/ex/data/media/desc1.xml
<?xml version="1.0" ?>
<!DOCTYPE model SYSTEM "../eol.dtd">
<!--
     Extracts all texts
-->
<model name="media">

<import model="../datatypes.xml" />

<!-- functions used by some script axioms -->
<script src="media.js" />

<!-- all references to resources below will be resolved relative to this base url -->
<base url="../../../data"/>

<class id="text_record" prune="0.05">
  
  <pattern id="media_near_title" type="pattern" cover="0.3" log="0" enabled="1">
    ^ $title <tok/>{0,10} $description
  </pattern>
  
  <pattern id="similar_title_desc" type="script" cover="0.6" p="-1" cond="all">
    altSimilarToText($title, $description) >= 0.2
  </pattern>
  
  <attribute id="title" type="name" card="1" prior="0.01" eng="0.7" log="0" prune="0.1">
    <pattern id="words1"> <tok>^[^&lt;]</tok> </pattern>
    <pattern id="words2"> <tok>^[^&lt;]</tok>{2,5} </pattern>
    <pattern id="words3"> <tok>^[^&lt;]</tok>{6,35} </pattern>

    <value>

      <or>
        <pattern p="0.6"> <tag name="caption"/> <pattern ref="words1"/> <tag name="/caption"/> </pattern>
        <pattern p="0.7"> <tag name="caption"/> <pattern ref="words2"/> <tag name="/caption"/> </pattern>
        <pattern p="0.8"> <tag name="caption"/> <pattern ref="words3"/> <tag name="/caption"/> </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="h1"/>      <pattern ref="words1"/> <tag name="/h1"/> </pattern>
        <pattern p="0.7"> <tag name="h1"/>      <pattern ref="words2"/> <tag name="/h1"/> </pattern>
        <pattern p="0.8"> <tag name="h1"/>      <pattern ref="words3"/> <tag name="/h1"/> </pattern>
        <pattern p="0.8" type="xpath" log="0"> //*[(local-name()='h1' or local-name()='H1')] </pattern>
      </or>
      <or>
        <pattern p="0.6" log="0"> <tag name="h2"/>      <pattern ref="words1"/> <tag name="/h2"/> </pattern>
        <pattern p="0.7" log="0"> <tag name="h2"/>      <pattern ref="words2"/> <tag name="/h2"/> </pattern>
        <pattern p="0.8" log="0"> <tag name="h2"/>      <pattern ref="words3"/> <tag name="/h2"/> </pattern>
        <pattern p="0.8" type="xpath" log="0"> //*[(local-name()='h2' or local-name()='H2')] </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="h3"/>      <pattern ref="words1"/> <tag name="/h3"/> </pattern>
        <pattern p="0.7"> <tag name="h3"/>      <pattern ref="words2"/> <tag name="/h3"/> </pattern>
        <pattern p="0.8"> <tag name="h3"/>      <pattern ref="words3"/> <tag name="/h3"/> </pattern>
        <pattern p="0.8" type="xpath" log="0"> //*[(local-name()='h3' or local-name()='H3')] </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="h4"/>      <pattern ref="words1"/> <tag name="/h4"/> </pattern>
        <pattern p="0.7"> <tag name="h4"/>      <pattern ref="words2"/> <tag name="/h4"/> </pattern>
        <pattern p="0.8"> <tag name="h4"/>      <pattern ref="words3"/> <tag name="/h4"/> </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="h5"/>      <pattern ref="words1"/> <tag name="/h5"/> </pattern>
        <pattern p="0.7"> <tag name="h5"/>      <pattern ref="words2"/> <tag name="/h5"/> </pattern>
        <pattern p="0.8"> <tag name="h5"/>      <pattern ref="words3"/> <tag name="/h5"/> </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="p"/>      <pattern ref="words1"/> <tag name="/p"/> </pattern>
        <pattern p="0.7"> <tag name="p"/>      <pattern ref="words2"/> <tag name="/p"/> </pattern>
        <pattern p="0.8"> <tag name="p"/>      <pattern ref="words3"/> <tag name="/p"/> </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="div"/>      <pattern ref="words1"/> <tag name="/div"/> </pattern>
        <pattern p="0.7"> <tag name="div"/>      <pattern ref="words2"/> <tag name="/div"/> </pattern>
        <pattern p="0.8"> <tag name="div"/>      <pattern ref="words3"/> <tag name="/div"/> </pattern>
      </or>
      <or>
        <pattern p="0.6"> <tag name="strong"/>      <pattern ref="words1"/> <tag name="/strong"/> </pattern>
        <pattern p="0.7"> <tag name="strong"/>      <pattern ref="words2"/> <tag name="/strong"/> </pattern>
        <pattern p="0.8"> <tag name="strong"/>      <pattern ref="words3"/> <tag name="/strong"/> </pattern>
      </or>
      
      <pattern p="0.005"> <tok/>? (Sendung) <tok/>? </pattern>
      <pattern p="0"> (Wirtschaft|<tok/> zum Thema) </pattern>
      <pattern p="0.005"> <tok/>{0,3} (op social media|bekeken) </pattern>
      
      <pattern type="script" cover="0.8" p="-1">
        <![CDATA[
    	getBlacklistedWordCnt($) <= 1 && getBlacklistedWordPortion($) < 0.1
    	]]>
  	  </pattern>

      <pattern type="script" cover="1" p="-1">
      	!isBlacklisted($)
      </pattern>
      
      <pattern type="script" cover="1" p="-1">
    	!containsFormObjects($)
  	  </pattern>
  	  
      <length><distribution min="1" max="30" /></length>

      <pattern cover="0.2" type="format"> has_one_parent </pattern> <!-- there may easily be spans inside a heading -->
      <pattern cover="1" type="format"> fits_in_parent </pattern>
      <pattern cover="1" type="format"> no_crossed_inline_tags </pattern>
      <pattern cover="1" type="format"> no_crossed_block_tags </pattern>
    </value>
  </attribute>


  <attribute id="description" type="text" card="0-3" prior="0.01" eng="0.7" log="0" prune="0.1">
    <value>
      <pattern id="xp1_desc" type="xpath" p="0.8" log="0">
        //*[(local-name()='p' or local-name()='div')]
      </pattern>
      
      <!-- lowercase (or true case) tag names result from XHTML pages, but HTML pages always yield uppercase elements in the Neko implementation -->
      <pattern id="xp2_desc" type="xpath" p="0.8" log="0">
        //*[(local-name()='P' or local-name()='DIV')]
      </pattern>
      
      <pattern type="script" cover="0.8" p="-1">
        <![CDATA[
    	getBlacklistedWordCnt($) <= 1 && getBlacklistedWordPortion($) < 0.1
    	]]>
  	  </pattern>

      <pattern type="script" cover="1" p="-1">
      	!isBlacklisted($)
      </pattern>
      
      <pattern type="script" cover="1" p="-1">
    	!containsFormObjects($)
  	  </pattern>
      
      <length><distribution min="5" max="500" /></length>

      <pattern cover="0.2" type="format"> has_one_parent </pattern> <!-- there may easily be spans inside a description -->
      <pattern cover="1" type="format"> fits_in_parent </pattern>
      <pattern cover="1" type="format"> no_crossed_inline_tags </pattern>
      <pattern cover="1" type="format"> no_crossed_block_tags </pattern>
    </value>
  </attribute>

</class>

</model>
